package Telas;

import javax.swing.JOptionPane;

public class TelaGastoCalorico extends javax.swing.JFrame {

    public TelaGastoCalorico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlbTituloCGC = new javax.swing.JLabel();
        jrbMulher = new javax.swing.JRadioButton();
        jrbHomem = new javax.swing.JRadioButton();
        jlbAltura = new javax.swing.JLabel();
        jlbPeso = new javax.swing.JLabel();
        jlbIdade = new javax.swing.JLabel();
        jlbNivelAtividade = new javax.swing.JLabel();
        jtfPeso = new javax.swing.JTextField();
        jtfAltura = new javax.swing.JTextField();
        jtfIdade = new javax.swing.JTextField();
        jcbNivelAtividade = new javax.swing.JComboBox<>();
        jbtCalcularGasto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlbGastoBasal = new javax.swing.JLabel();
        jlbGastoTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gasto Calórico");
        setSize(new java.awt.Dimension(500, 400));

        jlbTituloCGC.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jlbTituloCGC.setText("Cálculo de Gasto Calórico");

        buttonGroup1.add(jrbMulher);
        jrbMulher.setText("Mulher");

        buttonGroup1.add(jrbHomem);
        jrbHomem.setText("Homem");
        jrbHomem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbHomemActionPerformed(evt);
            }
        });

        jlbAltura.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jlbAltura.setText("Altura (cm):");

        jlbPeso.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jlbPeso.setText("Peso (kg):");

        jlbIdade.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jlbIdade.setText("Idade:");

        jlbNivelAtividade.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jlbNivelAtividade.setText("Nível de Atividade:");

        jcbNivelAtividade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Sedentário", "Leve", "Moderado", "Ativo", "Extremamente Ativo" }));

        jbtCalcularGasto.setBackground(new java.awt.Color(0, 153, 0));
        jbtCalcularGasto.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jbtCalcularGasto.setText("Calcular");
        jbtCalcularGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCalcularGastoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbTituloCGC)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jrbMulher)
                        .addGap(49, 49, 49)
                        .addComponent(jrbHomem))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbPeso)
                            .addComponent(jlbAltura)
                            .addComponent(jlbIdade))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfIdade, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jtfAltura)
                            .addComponent(jtfPeso)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbNivelAtividade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbNivelAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtCalcularGasto))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTituloCGC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbMulher)
                    .addComponent(jrbHomem))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPeso)
                    .addComponent(jtfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAltura)
                    .addComponent(jtfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbIdade)
                    .addComponent(jtfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNivelAtividade)
                    .addComponent(jcbNivelAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCalcularGasto)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jlbGastoBasal.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jlbGastoBasal.setText("Gasto Basal:");

        jlbGastoTotal.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jlbGastoTotal.setText("Gasto Total:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbGastoBasal)
                    .addComponent(jlbGastoTotal))
                .addContainerGap(383, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlbGastoBasal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbGastoTotal)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbHomemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbHomemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbHomemActionPerformed

    private void jbtCalcularGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalcularGastoActionPerformed
        if (!jrbMulher.isSelected() && !jrbHomem.isSelected()) {
            JOptionPane.showMessageDialog(null, "Por favor, escolha o sexo.");
        } else if (jtfAltura.getText().isEmpty() || jtfPeso.getText().isEmpty() || jtfIdade.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos.");
        } else if (jcbNivelAtividade.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione o nível de atividade.");
        } else {
            String testePeso = jtfPeso.getText();
            boolean palavra = testePeso.matches("\\d{1,3}||\\d{1,3},\\d{1,3}");
            String testeAltura = jtfAltura.getText();
            boolean palavra2 = testeAltura.matches("\\d{1,2},\\d{2}");
            String testeIdade = jtfIdade.getText();
            boolean palavra3 = testeIdade.matches("\\d{1,3}");

            if (palavra && palavra2 && palavra3) {
                String replaceAltura = jtfAltura.getText().replace(",", ".");
                Double altura = Double.parseDouble(replaceAltura);
                String replacePeso = jtfPeso.getText().replace(",", ".");
                Double peso = Double.parseDouble(replacePeso);
                Integer idade = Integer.parseInt(jtfIdade.getText());
                Double calBasal;
                if (jrbHomem.isSelected()) {
                    calBasal = 66 + (13.8*peso) + (5*altura) - (6.8* idade);
                    
                } else {
                    calBasal = 655 + (9.6*peso) + (1.9*altura) - (4.7* idade);
                }
                jlbGastoBasal.setText("Gasto Basal: " + calBasal +"kcal.");
                
                Double calTotal = null;
                switch (jcbNivelAtividade.getSelectedIndex()) {
                    case 1 -> calTotal = calBasal *1.2;
                    case 2 -> calTotal = calBasal *1.375;
                    case 3 -> calTotal = calBasal *1.55;
                    case 4 -> calTotal = calBasal *1.725;
                    case 5 -> calTotal = calBasal *1.9;
                }
                jlbGastoTotal.setText("Gasto total: " + calTotal + "kcal.");
            }
            if (!palavra) {
                JOptionPane.showMessageDialog(null, "Peso inválido, preencha no formato 'kg,ggg'.");
            }
            if (!palavra2) {
                JOptionPane.showMessageDialog(null, "Altura inválida, preencha no formato 'm,cmcm'.");
            }
            if (!palavra3) {
                JOptionPane.showMessageDialog(null, "Idade inválida.");
            }
        }

    }//GEN-LAST:event_jbtCalcularGastoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGastoCalorico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtCalcularGasto;
    private javax.swing.JComboBox<String> jcbNivelAtividade;
    private javax.swing.JLabel jlbAltura;
    private javax.swing.JLabel jlbGastoBasal;
    private javax.swing.JLabel jlbGastoTotal;
    private javax.swing.JLabel jlbIdade;
    private javax.swing.JLabel jlbNivelAtividade;
    private javax.swing.JLabel jlbPeso;
    private javax.swing.JLabel jlbTituloCGC;
    private javax.swing.JRadioButton jrbHomem;
    private javax.swing.JRadioButton jrbMulher;
    private javax.swing.JTextField jtfAltura;
    private javax.swing.JTextField jtfIdade;
    private javax.swing.JTextField jtfPeso;
    // End of variables declaration//GEN-END:variables
}
