package Telas;

import javax.swing.JOptionPane;

public class TelaRecomendacoes extends javax.swing.JFrame {

    public TelaRecomendacoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbRecomendacoes = new javax.swing.JLabel();
        jlbCaloriasDiarias = new javax.swing.JLabel();
        jtfCalorias = new javax.swing.JTextField();
        btnCalcularCalorias = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlbCarboidratos = new javax.swing.JLabel();
        jlbProteina = new javax.swing.JLabel();
        jlbGordura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recomendações");
        setPreferredSize(new java.awt.Dimension(500, 400));
        setSize(new java.awt.Dimension(500, 400));

        jlbRecomendacoes.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jlbRecomendacoes.setText("Recomendações");

        jlbCaloriasDiarias.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jlbCaloriasDiarias.setText("Calorias Diárias (kcal):");

        btnCalcularCalorias.setBackground(new java.awt.Color(0, 153, 0));
        btnCalcularCalorias.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnCalcularCalorias.setText("Calcular");
        btnCalcularCalorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCaloriasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCalcularCalorias)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlbRecomendacoes)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jlbCaloriasDiarias)
                            .addGap(18, 18, 18)
                            .addComponent(jtfCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbRecomendacoes)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCaloriasDiarias)
                    .addComponent(jtfCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcularCalorias)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jlbCarboidratos.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jlbCarboidratos.setText("Carboidratos (50%):");

        jlbProteina.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jlbProteina.setText("Proteína (25%):");

        jlbGordura.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jlbGordura.setText("Gordura (25%):");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbCarboidratos)
                    .addComponent(jlbProteina)
                    .addComponent(jlbGordura))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jlbCarboidratos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbProteina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbGordura)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularCaloriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCaloriasActionPerformed
        if (jtfCalorias.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, preencha o campo Calorias Diárias.");
        } else {
            String testeCalorias = jtfCalorias.getText();
            boolean palavra = testeCalorias.matches("\\d{1,5}");
            if (palavra) {
                Integer calorias = Integer.parseInt(jtfCalorias.getText());
                double carboidratos = (calorias * 0.5) / 4;
                double proteina = (calorias * 0.25) / 4;
                double gordura = (calorias * 0.25) / 9;

                jlbCarboidratos.setText("Carboidratos(50%): " + carboidratos + "g.");
                jlbProteina.setText("Proteína(25%): " + proteina + "g.");
                jlbGordura.setText("Gordura(25%): " + gordura + "g.");
            } else {
                JOptionPane.showMessageDialog(null, "Valor inválido para Calorias, informe um número inteiro de até 5 dígitos.");
            }
        }
    }//GEN-LAST:event_btnCalcularCaloriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRecomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRecomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRecomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRecomendacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRecomendacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularCalorias;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlbCaloriasDiarias;
    private javax.swing.JLabel jlbCarboidratos;
    private javax.swing.JLabel jlbGordura;
    private javax.swing.JLabel jlbProteina;
    private javax.swing.JLabel jlbRecomendacoes;
    private javax.swing.JTextField jtfCalorias;
    // End of variables declaration//GEN-END:variables
}
