package Telas;

import javax.swing.JOptionPane;

public class TelaIMC extends javax.swing.JFrame {

    public TelaIMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCalcIMC = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        jtfAltura = new javax.swing.JTextField();
        jtfPeso = new javax.swing.JTextField();
        jbtCalcularIMC = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlbInterpretacao = new javax.swing.JLabel();
        jlbResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("IMC");
        setPreferredSize(new java.awt.Dimension(500, 500));

        lblCalcIMC.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblCalcIMC.setText("Cálculo de IMC");

        lblAltura.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblAltura.setText("Altura (m):");

        lblPeso.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lblPeso.setText("Peso (kg):");

        jtfAltura.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jtfPeso.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N

        jbtCalcularIMC.setBackground(new java.awt.Color(0, 153, 0));
        jbtCalcularIMC.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jbtCalcularIMC.setText("Calcular");
        jbtCalcularIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCalcularIMCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblAltura)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblCalcIMC)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblPeso)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtfPeso)))
                    .addComponent(jbtCalcularIMC))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCalcIMC)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltura)
                    .addComponent(jtfAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(jtfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCalcularIMC)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jlbInterpretacao.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jlbInterpretacao.setText("Interpretação:");

        jlbResultado.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jlbResultado.setText("Resultado:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbInterpretacao)
                    .addComponent(jlbResultado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jlbResultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbInterpretacao)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCalcularIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalcularIMCActionPerformed

        if (jtfPeso.getText().isEmpty() || jtfAltura.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha ambos os campos Altura e Peso. ");
        } else {
            String testeAltura = jtfAltura.getText();
            boolean palavra = testeAltura.matches("\\d{1,2},\\d{2}");
            String testePeso = jtfPeso.getText();
            boolean palavra2 = testePeso.matches("\\d{1,3}||\\d{1,3},\\d{1,3}");
            if (palavra == true && palavra2 == true) {

                String replaceAltura = jtfAltura.getText().replace(",", ".");
                Double altura = Double.parseDouble(replaceAltura);
                String replacePeso = jtfPeso.getText().replace(",", ".");
                Double peso = Double.parseDouble(replacePeso);

                Double imc = peso / (altura * altura);

                jlbResultado.setText("Resultado: IMC = " + imc);
                if (imc < 18.5) {
                    jlbInterpretacao.setText("Interpretação: Magreza");
                } else if (imc >= 18.5 && imc < 25) {
                    jlbInterpretacao.setText("Interpretação: Normal");
                } else if (imc >= 25 && imc < 30) {
                    jlbInterpretacao.setText("Interpretação: Sobrepeso");
                } else if (imc >= 30 && imc < 40) {
                    jlbInterpretacao.setText("Interpretação: Obesidade");
                } else {
                    jlbInterpretacao.setText("Interpretação: Obesidade Grave");
                }
            } else if (palavra == false) {
                JOptionPane.showMessageDialog(null, "Altura inválida, preencha no formato 'm,cmcm'. ");
            } else if (palavra2 == false) {
                JOptionPane.showMessageDialog(null, "Peso inválido, preencha no formato 'kg,ggg'. ");
            }
        }


    }//GEN-LAST:event_jbtCalcularIMCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaIMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtCalcularIMC;
    private javax.swing.JLabel jlbInterpretacao;
    private javax.swing.JLabel jlbResultado;
    private javax.swing.JTextField jtfAltura;
    private javax.swing.JTextField jtfPeso;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblCalcIMC;
    private javax.swing.JLabel lblPeso;
    // End of variables declaration//GEN-END:variables
}
